use_frameworks!

target 'SwiftAudioPlayer_Example' do
  platform :ios, '10.0'  

  pod 'SwiftAudioPlayerKuama', :path => '../'

  target 'SwiftAudioPlayer_Tests' do
    inherit! :search_paths    
  end
end
